# Generated by Django 4.1.3 on 2023-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprawa',
            name='data_zamkniecia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
