# Generated by Django 4.1.3 on 2022-11-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obywatel',
            name='imie',
            field=models.CharField(max_length=22),
        ),
    ]
