# Generated by Django 4.1.3 on 2022-11-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0002_alter_obywatel_imie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obywatel',
            options={'ordering': ('imie',)},
        ),
    ]
