# Generated by Django 4.1.3 on 2022-11-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0003_alter_obywatel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddzial',
            name='kierownik',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='komenda.pracownik'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='id_oddzialu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='komenda.oddzial'),
        ),
        migrations.AlterField(
            model_name='sprawa',
            name='id_oddzialu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='komenda.oddzial'),
        ),
        migrations.AlterField(
            model_name='szkoda',
            name='samochod',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='komenda.samochod'),
        ),
    ]
