# Generated by Django 4.1.3 on 2022-11-21 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0004_alter_oddzial_kierownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddzial',
            name='kierownik',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='komenda.pracownik'),
        ),
    ]
