# Generated by Django 4.1.3 on 2022-11-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0009_alter_oddzial_kierownik_alter_pracownik_id_oddzialu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pracownik',
            name='id_oddzialu',
        ),
    ]
