# Generated by Django 4.1.3 on 2022-11-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0010_remove_pracownik_id_oddzialu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='id_oddzialu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='komenda.oddzial'),
        ),
    ]
