# Generated by Django 4.1.3 on 2022-11-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0011_pracownik_id_oddzialu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='szkoda',
            name='samochod',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='komenda.samochod'),
        ),
    ]
