# Generated by Django 4.1.3 on 2022-12-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0004_alter_oddzial_kierownik_alter_pracownik_id_oddzialu_and_more'),
        ('komenda', '0012_alter_szkoda_samochod'),
    ]

    operations = [
    ]
