# Generated by Django 4.1.3 on 2023-01-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0013_merge_20221219_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddzial',
            name='kierownik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komenda.pracownik'),
        ),
    ]
