# Generated by Django 4.1.3 on 2023-01-15 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0014_alter_oddzial_kierownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddzial',
            name='kierownik',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='komenda.pracownik'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='id_oddzialu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='komenda.oddzial'),
        ),
    ]
