# Generated by Django 4.1.3 on 2023-01-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('komenda', '0016_alter_pracownik_id_oddzialu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddzial',
            name='kierownik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='komenda.pracownik'),
        ),
        migrations.AlterField(
            model_name='pracownik',
            name='id_oddzialu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='komenda.oddzial'),
        ),
        migrations.AlterField(
            model_name='sprawa',
            name='id_oddzialu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='komenda.oddzial'),
        ),
        migrations.AlterField(
            model_name='szkoda',
            name='samochod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='komenda.samochod'),
        ),
    ]
